version: '3.8'

services:
  db:
    image: mysql:8.0.35
    container_name: payment_links_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_payment_links
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: payment_links_app
    ports:
      - "8081:8081"
    env_file: 
      - .env
    depends_on:
      - db

volumes:
  db_data:


